// <auto-generated />
using System;
using HealthExam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthExam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthExamDbContext))]
    [Migration("20260917055059_AddHisSignedFileInfoToExamRecord")]
    partial class AddHisSignedFileInfoToExamRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("HEX_ParaclinicalOrderNo");

            modelBuilder.HasSequence("HEX_ParaclinicalVendorLineNo");

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackage", b =>
                {
                    b.Property<Guid>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PackageID");

                    b.HasIndex("DivisionID", "PackageCode")
                        .IsUnique();

                    b.ToTable("HEX_ExamPackage", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackageService", b =>
                {
                    b.Property<Guid>("PackageServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("PackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("ParaclinicalKind")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("");

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("ServiceCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("ServiceGroupCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<long>("ServiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.HasKey("PackageServiceID");

                    b.HasIndex("PackageID", "OrderNo")
                        .HasDatabaseName("IX_HEX_PkgService_Pkg")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("PackageID", "ServiceID")
                        .IsUnique();

                    b.ToTable("HEX_ExamPackageService", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.MasterDataOption", b =>
                {
                    b.Property<Guid>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("ParentCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.HasKey("OptionID");

                    b.HasIndex("DivisionID", "Category", "Code")
                        .IsUnique();

                    b.HasIndex("DivisionID", "Category", "IsActive", "OrderNo");

                    b.HasIndex("DivisionID", "Category", "ParentCode", "IsActive");

                    b.ToTable("HEX_MasterDataOption", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.Organization", b =>
                {
                    b.Property<Guid>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("ContactEmail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("ContactName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("ContactPhone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("TaxCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.HasKey("OrganizationID");

                    b.HasIndex("DivisionID", "OrgCode")
                        .IsUnique();

                    b.HasIndex("DivisionID", "OrgName")
                        .HasDatabaseName("IX_HEX_Org_Name")
                        .HasFilter("\"IsActive\"");

                    b.ToTable("HEX_Organization", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Common.AuditLog", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("ActorID")
                        .HasColumnType("bigint");

                    b.Property<short>("ActorKind")
                        .HasColumnType("smallint");

                    b.Property<string>("ActorName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<short?>("FromState")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<short?>("ToState")
                        .HasColumnType("smallint");

                    b.Property<string>("TraceID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.HasKey("AuditID");

                    b.HasIndex("DivisionID", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Audit_Division");

                    b.HasIndex("EntityType", "EntityID", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_HEX_Audit_Entity");

                    b.ToTable("HEX_AuditLog", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.ExamForms.ExamGroupFormMapping", b =>
                {
                    b.Property<Guid>("MappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MedicalTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VariantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MappingID");

                    b.HasIndex("DivisionID", "VariantCode")
                        .IsUnique();

                    b.ToTable("HEX_ExamGroupFormMapping", (string)null);

                    b.HasData(
                        new
                        {
                            MappingID = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedActorKind = (short)1,
                            CreatedBy = 0L,
                            CreatedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionID = "DEV",
                            IsActive = true,
                            MedicalTypeCode = "KSK03",
                            ModifiedActorKind = (short)1,
                            ModifiedBy = 0L,
                            ModifiedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemplateCode = "KSK-TREN18TUOI",
                            VariantCode = "DTK_03"
                        },
                        new
                        {
                            MappingID = new Guid("f0000001-0000-0000-0000-000000000004"),
                            CreatedActorKind = (short)1,
                            CreatedBy = 0L,
                            CreatedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionID = "DHTESTING",
                            IsActive = true,
                            MedicalTypeCode = "KSK03",
                            ModifiedActorKind = (short)1,
                            ModifiedBy = 0L,
                            ModifiedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemplateCode = "KSK-TREN18TUOI",
                            VariantCode = "DTK_03"
                        });
                });

            modelBuilder.Entity("HealthExam.Domain.ExamForms.ExamGroupFormSectionMapping", b =>
                {
                    b.Property<Guid>("SectionMappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ItemGroupID")
                        .HasColumnType("integer");

                    b.Property<Guid>("MappingID")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SectionMappingID");

                    b.HasIndex("MappingID", "SectionKind")
                        .IsUnique();

                    b.ToTable("HEX_ExamGroupFormSectionMapping", (string)null);

                    b.HasData(
                        new
                        {
                            SectionMappingID = new Guid("f0000001-0000-0000-0000-000000000002"),
                            ItemGroupID = 64,
                            MappingID = new Guid("f0000001-0000-0000-0000-000000000001"),
                            SectionKind = "HISTORY"
                        },
                        new
                        {
                            SectionMappingID = new Guid("f0000001-0000-0000-0000-000000000003"),
                            ItemGroupID = 63,
                            MappingID = new Guid("f0000001-0000-0000-0000-000000000001"),
                            SectionKind = "EXTRA_INFO"
                        },
                        new
                        {
                            SectionMappingID = new Guid("f0000001-0000-0000-0000-000000000005"),
                            ItemGroupID = 64,
                            MappingID = new Guid("f0000001-0000-0000-0000-000000000004"),
                            SectionKind = "HISTORY"
                        },
                        new
                        {
                            SectionMappingID = new Guid("f0000001-0000-0000-0000-000000000006"),
                            ItemGroupID = 63,
                            MappingID = new Guid("f0000001-0000-0000-0000-000000000004"),
                            SectionKind = "EXTRA_INFO"
                        });
                });

            modelBuilder.Entity("HealthExam.Domain.ExamRecords.ExamRecord", b =>
                {
                    b.Property<Guid>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("AdmissionID")
                        .HasColumnType("bigint");

                    b.Property<string>("CancelReason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CancelledBy")
                        .HasColumnType("bigint");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("EmploymentRefID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExamFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExamFinishedAtEstimated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ExamLocationOptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("ExamReason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("ExamStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExamStartedAtEstimated")
                        .HasColumnType("boolean");

                    b.Property<string>("FormCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("FormID")
                        .HasColumnType("uuid");

                    b.Property<string>("HealthClassCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("HisEmrDataID")
                        .HasColumnType("uuid");

                    b.Property<string>("HisFormSyncError")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("HisFormSyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("HisFormTemplateID")
                        .HasColumnType("uuid");

                    b.Property<string>("HisSignedFileDocID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HisSignedFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ImportBatchID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InsuranceRefID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("PatientRefID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientSubjectOptionID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientTypeOptionID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentSourceOptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentSourceOther")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<short>("ProgressDone")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ProgressSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ProgressTotal")
                        .HasColumnType("smallint");

                    b.Property<string>("ProvinceCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("ProvinceName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RegisteredBy")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RelativeRefID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionID")
                        .HasColumnType("uuid");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SubmissionID")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WardCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("WardName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.HasKey("RecordID");

                    b.HasIndex("EmploymentRefID")
                        .HasDatabaseName("IX_HEX_Record_EmploymentRefID");

                    b.HasIndex("ExamLocationOptionID");

                    b.HasIndex("InsuranceRefID")
                        .HasDatabaseName("IX_HEX_Record_InsuranceRefID");

                    b.HasIndex("PackageID");

                    b.HasIndex("PatientRefID")
                        .HasDatabaseName("IX_HEX_Record_PatientRefID");

                    b.HasIndex("PatientSubjectOptionID");

                    b.HasIndex("PatientTypeOptionID");

                    b.HasIndex("PaymentSourceOptionID");

                    b.HasIndex("RelativeRefID")
                        .HasDatabaseName("IX_HEX_Record_RelativeRefID");

                    b.HasIndex("DivisionID", "RecordCode")
                        .IsUnique();

                    b.HasIndex("SessionID", "PatientRefID")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Record_Session_PatientRef")
                        .HasFilter("\"PatientRefID\" IS NOT NULL AND \"State\" NOT IN (4, 5)");

                    b.HasIndex("SessionID", "State")
                        .HasDatabaseName("IX_HEX_Record_Session");

                    b.ToTable("HEX_ExamRecord", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.ExamSessions.ExamSession", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExamDateTo")
                        .HasColumnType("date");

                    b.Property<string>("ExamPlace")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<int>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LastRecordNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationID")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("PackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SessionName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SessionID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PackageID");

                    b.HasIndex("DivisionID", "ExamDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Session_Date")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("DivisionID", "SessionCode")
                        .IsUnique();

                    b.HasIndex("DivisionID", "OrganizationID", "ExamDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_HEX_Session_Org");

                    b.ToTable("HEX_ExamSession", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedRecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<int>("ErrorRow")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorSummary")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionID")
                        .HasColumnType("uuid");

                    b.Property<string>("SheetName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("StoragePath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("SuccessRow")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRow")
                        .HasColumnType("integer");

                    b.HasKey("BatchID");

                    b.HasIndex("SessionID", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Import_Session");

                    b.ToTable("HEX_ImportBatch", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Imports.ImportBatchRow", b =>
                {
                    b.Property<long>("ImportRowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ImportRowID"));

                    b.Property<Guid>("BatchID")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("ErrorMessage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RecordID")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNo")
                        .HasColumnType("integer");

                    b.HasKey("ImportRowID");

                    b.HasIndex(new[] { "BatchID", "RowNo" }, "IX_HEX_ImportRow_Error")
                        .HasFilter("NOT \"IsValid\"");

                    b.HasIndex(new[] { "BatchID", "RowNo" }, "UX_HEX_ImportRow_Batch_RowNo")
                        .IsUnique();

                    b.ToTable("HEX_ImportBatchRow", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Integrations.IntegrationOutbox", b =>
                {
                    b.Property<long>("OutboxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("OutboxID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("LastError")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseSnippet")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("TraceID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OutboxID");

                    b.HasIndex("OrderID")
                        .HasDatabaseName("IX_HEX_Outbox_Order");

                    b.HasIndex("DivisionID", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Outbox_Dedup");

                    b.HasIndex("State", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("IX_HEX_Outbox_Pending")
                        .HasFilter("\"State\" IN (0, 2)");

                    b.ToTable("HEX_IntegrationOutbox", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Paraclinical.ParaclinicalOrder", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalOrderID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OrderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("OrderedByID")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderedByName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("ParaclinicalKind")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("");

                    b.Property<Guid>("RecordID")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("SentStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SessionID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourcePackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetSystem")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NONE");

                    b.HasKey("OrderID");

                    b.HasIndex("DivisionID", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Order_No");

                    b.HasIndex("RecordID", "OrderedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Order_Record")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("SessionID", "OrderedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Order_Session");

                    b.ToTable("HEX_ParaclinicalOrder", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Paraclinical.ParaclinicalOrderItem", b =>
                {
                    b.Property<Guid>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AttachmentID")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool?>("IsAbnormal")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<Guid>("RecordID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResultAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultRefID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultSourceKind")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("");

                    b.Property<string>("ServiceCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("ServiceGroupCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<long>("ServiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("SourcePackageID")
                        .HasColumnType("uuid");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<long?>("VendorLineNo")
                        .HasColumnType("bigint");

                    b.HasKey("OrderItemID");

                    b.HasIndex("DivisionID", "MessageID")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_OrderItem_MessageID")
                        .HasFilter("\"MessageID\" IS NOT NULL");

                    b.HasIndex("DivisionID", "VendorLineNo")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_OrderItem_VendorLineNo")
                        .HasFilter("\"VendorLineNo\" IS NOT NULL");

                    b.HasIndex("OrderID", "ServiceID")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_OrderItem_Service");

                    b.HasIndex("RecordID", "State")
                        .HasDatabaseName("IX_HEX_OrderItem_Record");

                    b.ToTable("HEX_ParaclinicalOrderItem", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("PatientRefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<short?>("BirthYear")
                        .HasColumnType("smallint");

                    b.Property<string>("BloodAboCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("BloodRhCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("EthnicityOptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("GenderID")
                        .HasColumnType("smallint");

                    b.Property<long?>("HisPatientID")
                        .HasColumnType("bigint");

                    b.Property<string>("HisSyncError")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("HisSyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateOnly?>("IdentityIssuedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdentityIssuerOptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("PhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("PreviousPatientRefID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileLineageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("PatientRefID");

                    b.HasIndex("EthnicityOptionID");

                    b.HasIndex("IdentityIssuerOptionID");

                    b.HasIndex("PreviousPatientRefID");

                    b.HasIndex("DivisionID", "HisPatientID")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Patient_Division_HisPatientID")
                        .HasFilter("\"IsActive\" AND \"HisPatientID\" IS NOT NULL AND \"HisPatientID\" > 0");

                    b.HasIndex("DivisionID", "IdentityNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Patient_Division_ActiveIdentity")
                        .HasFilter("\"IsActive\" AND \"IdentityNumber\" <> ''");

                    b.HasIndex("DivisionID", "PatientCode")
                        .HasDatabaseName("IX_HEX_Patient_Division_Code");

                    b.HasIndex("DivisionID", "ProfileLineageID", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Patient_Division_Lineage_Version");

                    b.ToTable("HEX_Patient", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.PatientEmployment", b =>
                {
                    b.Property<Guid>("EmploymentRefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTitle")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OccupationOptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgDeptName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<Guid>("PatientRefID")
                        .HasColumnType("uuid");

                    b.Property<string>("StaffCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.HasKey("EmploymentRefID");

                    b.HasIndex("OccupationOptionID");

                    b.HasIndex("PatientRefID")
                        .HasDatabaseName("IX_HEX_PatientEmployment_Patient");

                    b.ToTable("HEX_PatientEmployment", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.PatientInsurance", b =>
                {
                    b.Property<Guid>("InsuranceRefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("InsuranceNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("InsuranceObjectOptionID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientRefID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegistrationPlaceOptionID")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("InsuranceRefID");

                    b.HasIndex("InsuranceObjectOptionID");

                    b.HasIndex("PatientRefID")
                        .HasDatabaseName("IX_HEX_PatientInsurance_Patient");

                    b.HasIndex("RegistrationPlaceOptionID");

                    b.HasIndex("DivisionID", "InsuranceNumber")
                        .HasDatabaseName("IX_HEX_PatientInsurance_Number");

                    b.ToTable("HEX_PatientInsurance", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.PatientRelative", b =>
                {
                    b.Property<Guid>("RelativeRefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("IdentityNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientRefID")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("RelationshipCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("RelationshipOptionID")
                        .HasColumnType("uuid");

                    b.HasKey("RelativeRefID");

                    b.HasIndex("PatientRefID")
                        .HasDatabaseName("IX_HEX_PatientRelative_Patient");

                    b.ToTable("HEX_PatientRelative", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Webhooks.WebhookInbox", b =>
                {
                    b.Property<long>("InboxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("InboxID"));

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("EventID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastError")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("MessageID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<short>("ProcessState")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("RecordID")
                        .HasColumnType("uuid");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SubmissionID")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.HasKey("InboxID");

                    b.HasIndex("DivisionID", "EventID")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Inbox_Event");

                    b.HasIndex("DivisionID", "MessageID")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Inbox_MessageID")
                        .HasFilter("\"MessageID\" IS NOT NULL");

                    b.HasIndex("ProcessState", "NextAttemptAt", "ReceivedAt")
                        .HasDatabaseName("IX_HEX_Inbox_Pending")
                        .HasFilter("\"ProcessState\" IN (0, 2)");

                    b.ToTable("HEX_WebhookInbox", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackageService", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.ExamPackage", "Package")
                        .WithMany("Services")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("HealthExam.Domain.ExamForms.ExamGroupFormSectionMapping", b =>
                {
                    b.HasOne("HealthExam.Domain.ExamForms.ExamGroupFormMapping", "Mapping")
                        .WithMany("Sections")
                        .HasForeignKey("MappingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("HealthExam.Domain.ExamRecords.ExamRecord", b =>
                {
                    b.HasOne("HealthExam.Domain.Patients.PatientEmployment", "Employment")
                        .WithMany()
                        .HasForeignKey("EmploymentRefID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "ExamLocationOption")
                        .WithMany()
                        .HasForeignKey("ExamLocationOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Patients.PatientInsurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceRefID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.ExamPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientRefID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "PatientSubjectOption")
                        .WithMany()
                        .HasForeignKey("PatientSubjectOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "PatientTypeOption")
                        .WithMany()
                        .HasForeignKey("PatientTypeOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "PaymentSourceOption")
                        .WithMany()
                        .HasForeignKey("PaymentSourceOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Patients.PatientRelative", "Relative")
                        .WithMany()
                        .HasForeignKey("RelativeRefID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.ExamSessions.ExamSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employment");

                    b.Navigation("ExamLocationOption");

                    b.Navigation("Insurance");

                    b.Navigation("Package");

                    b.Navigation("Patient");

                    b.Navigation("PatientSubjectOption");

                    b.Navigation("PatientTypeOption");

                    b.Navigation("PaymentSourceOption");

                    b.Navigation("Relative");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealthExam.Domain.ExamSessions.ExamSession", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.ExamPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("HealthExam.Domain.Imports.ImportBatch", b =>
                {
                    b.HasOne("HealthExam.Domain.ExamSessions.ExamSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealthExam.Domain.Imports.ImportBatchRow", b =>
                {
                    b.HasOne("HealthExam.Domain.Imports.ImportBatch", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("HealthExam.Domain.Paraclinical.ParaclinicalOrder", b =>
                {
                    b.HasOne("HealthExam.Domain.ExamRecords.ExamRecord", "Record")
                        .WithMany()
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("HealthExam.Domain.Paraclinical.ParaclinicalOrderItem", b =>
                {
                    b.HasOne("HealthExam.Domain.Paraclinical.ParaclinicalOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.Patient", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "EthnicityOption")
                        .WithMany()
                        .HasForeignKey("EthnicityOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "IdentityIssuerOption")
                        .WithMany()
                        .HasForeignKey("IdentityIssuerOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Patients.Patient", "PreviousPatient")
                        .WithMany()
                        .HasForeignKey("PreviousPatientRefID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EthnicityOption");

                    b.Navigation("IdentityIssuerOption");

                    b.Navigation("PreviousPatient");
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.PatientEmployment", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "OccupationOption")
                        .WithMany()
                        .HasForeignKey("OccupationOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Patients.Patient", "Patient")
                        .WithMany("Employments")
                        .HasForeignKey("PatientRefID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OccupationOption");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.PatientInsurance", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "InsuranceObjectOption")
                        .WithMany()
                        .HasForeignKey("InsuranceObjectOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Patients.Patient", "Patient")
                        .WithMany("Insurances")
                        .HasForeignKey("PatientRefID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthExam.Domain.Catalogs.MasterDataOption", "RegistrationPlaceOption")
                        .WithMany()
                        .HasForeignKey("RegistrationPlaceOptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InsuranceObjectOption");

                    b.Navigation("Patient");

                    b.Navigation("RegistrationPlaceOption");
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.PatientRelative", b =>
                {
                    b.HasOne("HealthExam.Domain.Patients.Patient", "Patient")
                        .WithMany("Relatives")
                        .HasForeignKey("PatientRefID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackage", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("HealthExam.Domain.ExamForms.ExamGroupFormMapping", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("HealthExam.Domain.Imports.ImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("HealthExam.Domain.Paraclinical.ParaclinicalOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HealthExam.Domain.Patients.Patient", b =>
                {
                    b.Navigation("Employments");

                    b.Navigation("Insurances");

                    b.Navigation("Relatives");
                });
#pragma warning restore 612, 618
        }
    }
}
