// <auto-generated />
using System;
using HealthExam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthExam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthExamDbContext))]
    [Migration("20260824095039_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthExam.Domain.Common.AuditLog", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("ActorID")
                        .HasColumnType("bigint");

                    b.Property<short>("ActorKind")
                        .HasColumnType("smallint");

                    b.Property<string>("ActorName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<short?>("FromState")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<short?>("ToState")
                        .HasColumnType("smallint");

                    b.Property<string>("TraceID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.HasKey("AuditID");

                    b.HasIndex("DivisionID", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Audit_Division");

                    b.HasIndex("EntityType", "EntityID", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_HEX_Audit_Entity");

                    b.ToTable("HEX_AuditLog", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackage", b =>
                {
                    b.Property<Guid>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PackageID");

                    b.HasIndex("DivisionID", "PackageCode")
                        .IsUnique();

                    b.ToTable("HEX_ExamPackage", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackageService", b =>
                {
                    b.Property<Guid>("PackageServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("PackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("ParaclinicalKind")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("");

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("ServiceCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("ServiceGroupCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<long>("ServiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.HasKey("PackageServiceID");

                    b.HasIndex("PackageID", "OrderNo")
                        .HasDatabaseName("IX_HEX_PkgService_Pkg")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("PackageID", "ServiceID")
                        .IsUnique();

                    b.ToTable("HEX_ExamPackageService", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.ExamRecords.ExamRecord", b =>
                {
                    b.Property<Guid>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<short?>("BirthYear")
                        .HasColumnType("smallint");

                    b.Property<string>("CancelReason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CancelledBy")
                        .HasColumnType("bigint");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("ExamFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExamStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("FormID")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("GenderID")
                        .HasColumnType("smallint");

                    b.Property<string>("HealthClassCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("IdentityNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("ImportBatchID")
                        .HasColumnType("uuid");

                    b.Property<string>("InsuranceNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("JobTitle")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrgDeptName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("PackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("PatientCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<long>("PatientID")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<short>("ProgressDone")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ProgressSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ProgressTotal")
                        .HasColumnType("smallint");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RegisteredBy")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SessionID")
                        .HasColumnType("uuid");

                    b.Property<string>("StaffCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SubmissionID")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RecordID");

                    b.HasIndex("PackageID");

                    b.HasIndex("DivisionID", "RecordCode")
                        .IsUnique();

                    b.HasIndex("SessionID", "IdentityNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Record_Session_Identity")
                        .HasFilter("\"IdentityNumber\" <> '' AND \"State\" <> 4");

                    b.HasIndex("SessionID", "PatientCode")
                        .IsUnique()
                        .HasDatabaseName("UX_HEX_Record_Session_Patient")
                        .HasFilter("\"PatientCode\" <> '' AND \"State\" <> 4");

                    b.HasIndex("SessionID", "State")
                        .HasDatabaseName("IX_HEX_Record_Session");

                    b.ToTable("HEX_ExamRecord", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.ExamSessions.ExamSession", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExamDateTo")
                        .HasColumnType("date");

                    b.Property<string>("ExamPlace")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<int>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationID")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("PackageID")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SessionName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SessionID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PackageID");

                    b.HasIndex("DivisionID", "ExamDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HEX_Session_Date")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("DivisionID", "SessionCode")
                        .IsUnique();

                    b.HasIndex("DivisionID", "OrganizationID", "ExamDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_HEX_Session_Org");

                    b.ToTable("HEX_ExamSession", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.Organization", b =>
                {
                    b.Property<Guid>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("ContactEmail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("ContactName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("ContactPhone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<short>("CreatedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("ModifiedActorKind")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("TaxCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.HasKey("OrganizationID");

                    b.HasIndex("DivisionID", "OrgCode")
                        .IsUnique();

                    b.HasIndex("DivisionID", "OrgName")
                        .HasDatabaseName("IX_HEX_Org_Name")
                        .HasFilter("\"IsActive\"");

                    b.ToTable("HEX_Organization", (string)null);
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackageService", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.ExamPackage", "Package")
                        .WithMany("Services")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("HealthExam.Domain.ExamRecords.ExamRecord", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.ExamPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.ExamSessions.ExamSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealthExam.Domain.ExamSessions.ExamSession", b =>
                {
                    b.HasOne("HealthExam.Domain.Catalogs.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthExam.Domain.Catalogs.ExamPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("HealthExam.Domain.Catalogs.ExamPackage", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
